# Generated by Django 3.0.5 on 2020-04-01 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activix_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useractivity',
            options={'managed': True},
        ),
    ]
