# Generated by Django 3.0.5 on 2020-04-01 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activix_api', '0002_auto_20200401_1816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useractivity',
            name='endTime',
        ),
        migrations.RemoveField(
            model_name='useractivity',
            name='startTime',
        ),
        migrations.AddField(
            model_name='useractivity',
            name='activityID',
            field=models.ForeignKey(db_column='ActivityID', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='activix_api.Activity'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useractivity',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='duration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='activix_api.AuthUser'),
            preserve_default=False,
        ),
    ]
