# Generated by Django 3.0.5 on 2020-04-01 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activix_api', '0003_auto_20200401_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='activityID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='activix_api.Activity'),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='userActivityID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
