# Generated by Django 3.0.5 on 2020-04-01 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activix_api', '0004_auto_20200401_1826'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useractivity',
            old_name='duration',
            new_name='act_duration',
        ),
        migrations.RenameField(
            model_name='useractivity',
            old_name='date',
            new_name='rec_date',
        ),
    ]
