# Generated by Django 3.0.5 on 2020-04-01 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activix_api', '0005_auto_20200401_1828'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useractivity',
            old_name='rec_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='useractivity',
            old_name='act_duration',
            new_name='duration',
        ),
    ]
