# Generated by Django 3.0.5 on 2020-04-01 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activix_api', '0006_auto_20200401_1830'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='useractivity',
            table=None,
        ),
    ]
