# Generated by Django 3.0.5 on 2020-04-01 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activix_api', '0008_auto_20200401_1834'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useractivity',
            options={'managed': True},
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='userActivityID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
