# Generated by Django 3.0.5 on 2020-04-02 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activix_api', '0009_auto_20200401_1840'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useractivity',
            options={'managed': False},
        ),
    ]
