# Generated by Django 3.0.5 on 2020-04-02 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activix_api', '0010_auto_20200401_2009'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='useractivity',
            table='UserActivity',
        ),
    ]
